[build]
  command = "hugo --gc --minify -b $URL --themesDir ../../"
  publish = "public"

[build.environment]
  HUGO_THEME = "hugo-academic"
  HUGO_VERSION = "0.57.1"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL --themesDir ../../"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL --themesDir ../../"
